### ISSUE TITLE
EIP-1559

### ISSUE THREAD

**Issue by 3rror0x0** [ayushch80/instant-eth#3]
Sir. 
I am already check your **0xD0b2d6D92F71cb1F72C61BAcDef64f33e4f1eeBb**
Address. Your all Transection make EIP-1559 . Please i want to know how can i adjust my transection like you? 
Please Check this photo:
https://drive.google.com/file/d/1O1TPJ-AzAraBEHaixX9wnnCn4dK7yV8n/view?usp=sharing

**Comment by ayushch80** [comment]
describe your issue to me on telegram @ayushch80

**Comment by ayushch80** [comment]
BTW all the transactions made by the bot are EIP-1559 compatible , you **may be** using different JSON RPC url 
![image](https://user-images.githubusercontent.com/87753540/171267583-a387fac9-c906-480d-9282-9ab91c3e0d6e.png)
